import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	intro: [
		"intro",
		"domain/overview",
		"requirements/overview",
		"architecture/overview",
	],
	domain: [
		{ type: "autogenerated", dirName: "domain"}
	],
	requirements: [
		{ type: "autogenerated", dirName: "requirements"}
	],
	architecture: [
		{ type: "autogenerated", dirName: "architecture"}
	],
};

// noinspection JSUnusedGlobalSymbols
export default sidebars;
