import type {SidebarsConfig} from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
	intro: [
		"intro",
		"domain/overview",
		"requirements/overview",
		"architecture/overview",
	],
	domain: [
		"domain/overview",
		"domain/business-vision",
		"domain/core-domain-concepts",
		"domain/ubiquitous-language",
		{
			type: "category",
			label: "Bounded contexts",
			link: {type: "doc", id: "domain/bounded-contexts/overview"},
			items: [{type: "autogenerated", dirName: "domain/bounded-contexts"}],
			collapsed: false,
		},
		"domain/process-workflows",
		"domain/domain-events",
	],
	requirements: [
		"requirements/overview",
		"requirements/templates",
		"requirements/business-requirements",
		{
			type: "category",
			label: "Functional Requirements",
			link: {type: "doc", id: "requirements/functional/overview"},
			items: [{type: "autogenerated", dirName: "requirements/functional"}],
			collapsed: false,
		},
		"requirements/non-functional-requirements",
		"requirements/user-stories",
		"requirements/system-requirements",
	],
	architecture: [
		"architecture/overview",
	],
};

// noinspection JSUnusedGlobalSymbols
export default sidebars;
